### PR TITLE
Fixed home address inputs and keyboard behaviour

### LINKED ISSUE #180: First time use keyboard fix
First time use views are not working well with keyboard

### PR DESCRIPTION
**Pull request by Kaemppi**
resolves #180

### CODE REVIEW

File: src/components/screens/new-user-screen.tsx [hunk 1]
```diff
@@ -101,50 +103,68 @@ class NewUserScreen extends React.Component<Props, State> {
...
   }
 
+  /**
+   * Content render method
+   */
+  public renderContent = () => {
+    const {
+      currentScreen
+    } = this.state;
+    return (
```
Comment (Daniilmass) [inline src/components/screens/new-user-screen.tsx:141]:
```suggestion
    } = this.state;
    
    return (
```

**Review by Daniilmass — CHANGES_REQUESTED** [review]
