### PR TITLE
Feature 237 UI routing style fixes

### LINKED ISSUE #237: UI routing style fixes

### PR DESCRIPTION
**Pull request by Daniilmass**
Closes #237

### CODE REVIEW

File: src/components/screens/saved-routes-screen.tsx [hunk 1]
```diff
@@ -179,30 +178,58 @@ class SavedRoutes extends React.Component<Props, State> {
...
+        //       />
+        //     </View>
+        //   </TouchableHighlight>
+        //   <IconButton
+        //     key={ route.routePoints }
+        //     style={ form.deleteSavedRoutesButton }
+        //     icon="delete"
+        //     onPress={ () => this.openDeleteDialog(route) }
+        //   />
+        // </>
```
Comment (Daniilmass) [inline src/components/screens/saved-routes-screen.tsx:203]: Can this be removed?
